name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python_version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev python3-dev libssl-dev zlib1g-dev libgdbm-dev libncurses5-dev libreadline-dev libbz2-dev libsqlite3-dev tk-dev libgdbm-compat-dev liblzma-dev libffi-dev uuid-dev tar bzip2 gzip openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython kivy

      - name: Build APK with Buildozer
        run: |
          # تنظيف البيئة قبل البدء
          buildozer android clean
          yes | buildozer -v android debug
        continue-on-error: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FireSkeleton-APK
          path: bin/*.apk
