name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04 # تحديد نسخة النظام لضمان التوافق
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        # استخدام الأداة الرسمية والأكثر استقراراً
        uses: kivy/buildozer-action@master
        with:
          save_build_caches: true
          push_build_caches: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FireSkeleton-APK
          path: bin/*.apk
